### ISSUE TITLE
Request - Coverting member audit tokens to corp tools

### ISSUE THREAD

**Issue by Marsbar12101** [pvyParts/allianceauth-corp-tools#21]
Like the title said, it would be nice to be able to switch from member audit to corp tools. Without getting everybody to sign up again

**Comment by pvyParts** [comment]
This can be done with the `manage.py corptools_import_tokens --minimal-scopes`

importat to note that the tokens are different so some modules will need new tokens, you can disable the modules or set them to not factor into the  "character active" stat by adding the following to your local.py ( quick glance you may need to adjust )

```python
CT_CHAR_ACTIVE_IGNORE_ROLES_MODULE = True
```
